language: node_js
node_js:
- "0.10"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq unison
- npm install -g grunt-cli
install: npm install
script: grunt
branches:
  only:
  - master
